name: test workflow
on: push

jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome job
          run: |
            echo "my welcome job"
            ls -la

    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: 2nd welcome job
          run: |
            echo "my welcome 2nd job"
            ls -la
